//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var launchScreen: launchScreen { .init(source: .init(bundle: bundle, tableName: "LaunchScreen", preferredLanguages: preferredLanguages, locale: locale)) }
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }

    func launchScreen(preferredLanguages: [String]) -> launchScreen {
      .init(source: .init(bundle: bundle, tableName: "LaunchScreen", preferredLanguages: preferredLanguages, locale: locale))
    }
    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.launchScreen` struct is generated, and contains static references to 0 localization keys.
    struct launchScreen {
      let source: RswiftResources.StringResource.Source
    }

    /// This `_R.string.localizable` struct is generated, and contains static references to 8 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// ru translation: Не хочу отвечать
      ///
      /// Key: declineAnswer
      ///
      /// Locales: ru
      var declineAnswer: RswiftResources.StringResource { .init(key: "declineAnswer", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ru translation: Понравился гид?
      ///
      /// Key: guideRateTitle
      ///
      /// Locales: ru
      var guideRateTitle: RswiftResources.StringResource { .init(key: "guideRateTitle", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ru translation: Как вам подача информации?
      ///
      /// Key: informationRateTitle
      ///
      /// Locales: ru
      var informationRateTitle: RswiftResources.StringResource { .init(key: "informationRateTitle", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ru translation: Удобная навигации между шагами?
      ///
      /// Key: navigationRateTitle
      ///
      /// Locales: ru
      var navigationRateTitle: RswiftResources.StringResource { .init(key: "navigationRateTitle", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ru translation: Далее
      ///
      /// Key: next
      ///
      /// Locales: ru
      var next: RswiftResources.StringResource { .init(key: "next", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ru translation: Как вам тур в целом?
      ///
      /// Key: overallRateTitle
      ///
      /// Locales: ru
      var overallRateTitle: RswiftResources.StringResource { .init(key: "overallRateTitle", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ru translation: Офигенно, вы дошли до конца! Расскажите, как вам?
      ///
      /// Key: reviewRateTitle
      ///
      /// Locales: ru
      var reviewRateTitle: RswiftResources.StringResource { .init(key: "reviewRateTitle", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }

      /// ru translation: Написать отзыв
      ///
      /// Key: writeReview
      ///
      /// Locales: ru
      var writeReview: RswiftResources.StringResource { .init(key: "writeReview", tableName: "Localizable", source: source, developmentValue: nil, comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `customGray`.
    var customGray: RswiftResources.ColorResource { .init(name: "customGray", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 2 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `defaultThumb`.
    var defaultThumb: RswiftResources.ImageResource { .init(name: "defaultThumb", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `rateSliderBackground`.
    var rateSliderBackground: RswiftResources.ImageResource { .init(name: "rateSliderBackground", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
    }


    /// Storyboard `LaunchScreen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "LaunchScreen"
      func validate() throws {

      }
    }
  }
}